package edu.westga.cs6312.stock.controller;

import java.io.FileNotFoundException;
import java.util.Scanner;

import edu.westga.cs6312.stock.model.StockManager;
import edu.westga.cs6312.stock.view.StockTUI;

/**
 * Allows the user to select between the TUI and GUI versions of the
 * application.
 * 
 * @author Spencer Dent
 * @version 2021-05-02
 */
public class VersionChooser {
	private Scanner keyboardScanner;
	private StockManager stockManagerModel;

	/**
	 * Creates a new VersionChooser, instantiating its Scanner.
	 */
	public VersionChooser() {
		this.keyboardScanner = new Scanner(System.in);
	}

	/**
	 * Prompts the user to select a view version and calls the appropriate methods
	 * to create the selected view.
	 */
	public void chooseVersion() {
		while (this.stockManagerModel == null) {
			String fileName = this.getFileName();
			try {
				this.stockManagerModel = FileInteractor.readData(fileName);
			} catch (FileNotFoundException cannotFindFileAtPath) {
				System.out.println("Unable to locate data file with given name. Please try again.");
			}
		}
		this.runTextOption();
		this.keyboardScanner.close();
	}

	/**
	 * Prompts the user for a file name and returns the input from the user.
	 * 
	 * @return user provided file name
	 */
	private String getFileName() {
		System.out.print("Please enter the name of the data file: ");
		return this.keyboardScanner.nextLine();
	}

	/**
	 * Creates a StockTUI using the StockManager model generated by the
	 * FileInteractor, and calls its run method.
	 */
	private void runTextOption() {
		StockTUI textualUserInterface = new StockTUI(this.stockManagerModel);
		textualUserInterface.run();
	}
}
